# Site settings
title: Dust Edition
email: erik@hecanjog.com
description: > 
    Writing
baseurl: ""
url: "http://dustedition.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
